apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: backend
type: Opaque
stringData:
  DB_PASSWORD: "12345678"
  JWT_SECRET: "014ffc23305636ca26ee50d7dc56768c7ecbab7f7c9478f262d5591d2aacd5bf193ebbf6b77ccf462811f50588b90396ef58e62dad23e82e3f127e0d54964f23"
  EMAIL_PASSWORD: "ijkl rtny jycm bvjc"
  STRIPE_SECRET_KEY: "sk_test_51SIpVAGZNmNwx6zV2PcZlShsini2vQchCk3uIPYCE4TVUnRL0ZOcAQJpfkT5pvBWOdHC6f753Yl0fmsJE6gINPrt00SReMvCY8"
  STRIPE_WEBHOOK_SECRET: "whsec_yTrmcBjv5KrX5bE5LFGdLHoEyTkVUGfH"
  
